function h = fig_nova(largura_pol, altura_pol)
% FIG_NOVA  Figura invisivel com o estilo padrao do projeto.
%   largura e altura em polegadas (exportada a 150 dpi por fig_salvar).
  if nargin < 1, largura_pol = 8; end
  if nargin < 2, altura_pol = 3.2; end
  C = cores_propom();
  h = figure('visible', 'off', 'color', 'w');
  set(h, 'paperunits', 'inches', 'papersize', [largura_pol altura_pol], ...
         'paperposition', [0 0 largura_pol altura_pol], ...
         'position', [0 0 round(100*largura_pol) round(100*altura_pol)]);
  set(h, 'defaultaxesfontname', 'DejaVu Sans', 'defaultaxesfontsize', 9, ...
         'defaulttextfontname', 'DejaVu Sans', 'defaulttextfontsize', 9, ...
         'defaultaxesxcolor', C.sec, 'defaultaxesycolor', C.sec, ...
         'defaultaxesgridcolor', C.grade, 'defaultaxesgridalpha', 1, ...
         'defaultaxesbox', 'off', 'defaultaxestickdir', 'out', ...
         'defaultaxeslinewidth', 0.6, 'defaultlinelinewidth', 1.4, ...
         'defaultaxescolororder', [C.pro; C.lab; C.c3]);
end
